# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Edacious' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'StepSlider'
  pod ‘ScalingCarousel’
  pod 'XLPagerTabStrip', '~> 8.0'
  pod 'Cosmos', '~> 15.0'

end
